# Generated by Django 3.0 on 2020-10-14 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='last_visited',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
