# Generated by Django 3.0 on 2020-10-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201014_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=10)),
                ('cpu_usage', models.DecimalField(decimal_places=5, max_digits=10)),
                ('name', models.CharField(max_length=100)),
                ('difference_from_last_time', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
    ]
